spring.application.name=Sanitization-Management-System
server.port=${SERVER_PORT}

#Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# image size
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000

# Razorpay
razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}

#Admin Bootstrap
admin.bootstrap.enabled=${ADMIN_BOOTSTRAP_ENABLED}
admin.bootstrap.username=${ADMIN_BOOTSTRAP_USERNAME}
admin.bootstrap.name=${ADMIN_BOOTSTRAP_NAME}
admin.bootstrap.password=${ADMIN_BOOTSTRAP_PASSWORD}